#!/bin/bash

HOME="/data/data/com.termux/files/home"

REPO_DIRECTORY="$HOME/storage/downloads/termux"

source $HOME/.shortcuts/consts.sh

echo -e "${GREEN}\n$SEPARATOR\nAuto pull script for the directory:\n${NC}$REPO_DIRECTORY\n${GREEN}$SEPARATOR${NC}"

for repo in $(find "$REPO_DIRECTORY" -maxdepth 1 -type d); do
  if [ -d "$repo/.git" ]; then
    echo -e "Updating repository:\n$repo"
    echo -e "Do you want to force pull this repository ? (y/n)"
    read -n 1 -s -r -p ""
  
    cd "$repo"
    if [ "$REPLY" = "y" ]; then
      git fetch --all
      git reset --hard origin/main
      git checkout -- .
    else
      git pull
    fi
    echo -e "${YELLOW}$SEPARATOR${NC}"
  fi
done

echo -e "${GREEN}End of script : Press any key to exit ...${NC}"
read -n 1 -s -r -p ""